# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Task-Pluggable
version:      0.02
version_from: lib/Task/Pluggable.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Data::Inheritable:      0
    Module::Pluggable::Fast:       0
    Term::ANSIColor:               0
    Test::More:                    0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
